### ISSUE TITLE
Versions of modules

### ISSUE THREAD

**Issue by gabriel-fsa** [pythonlessons/CAPTCHA-solver#1]
Could you inform the versions of the modules used? As it was posted a long time ago, there are updated modules that are no longer compatible with the code, for example object_detection:

Traceback (most recent call last):
   File "train.py", line 55, in <module>
     from object_detection.utils import config_util
   File "C: \ Users \ gabri \ .conda \ envs \ py36 \ lib \ site-packages \ object_detection \ utils \ config_util.py", line 24, in <module>
     from object_detection.protos import eval_pb2
ImportError: cannot import name 'eval_pb2'

**Comment by iamrony777** [comment]
Install Object-Detection from Tensorflow

```
pip install tensorflow-object-detection
```
